name: Replace GitHub CDN Images

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:  # allow manual trigger

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Replace CDN images with local copies
        run: |
          python .github/scripts/replace_cdn_images.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Replace GitHub CDN images with local copies"
          git push
